config/routes.rb
Rails.application.routes.draw do
root 'page#home'
resource :quiz, only: [:show, :update]
end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :books
	validates :name, presence: true, length: { minimum: 10 }
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :author
	validates :title, presence: true, length: { minimum: 2 }
	validates :content, presence: true, length: { minimum: 150}
	validates :author, presence: true
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	belongs_to :book
	validates :book_id, presence: true
	validates :content, presence: true, length: { minimum: 100}
end

app/models/question.rb
class Question
  attr_accessor :answered, :sentence, :book, :choices

  def self.create(quiz)
    question = self.new
    question.pick_sentence
    question.get_choices(quiz.score)
    question
  end

  def initialize
    self.answered = false
    self.choices = Hash.new
  end

  def pick_sentence
    self.sentence = Sentence.random()
    author = self.sentence.author
    self.choices[author.name] = author.id
    self.book = self.sentence.book
  end

  def get_choices(score)
    sample_count = [(score/200)+1, 4].min
    remaining = Author.all.where("id != ?", self.sentence.author.id)
    remaining.sample(sample_count).each do |author|
      self.choices[author.name] = author.id
    end
  end

  def correct_author
    self.sentence.book.title
  end

  def correct_book
    self.sentence.author.name
  end

  def correct_answer
    self.sentence.author.id
  end

end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  attr_accessor :cur_question
  after_initialize :set_up

  def set_up
    self.over = false
    self.score || self.score = 0
    self.answer || self.new_question
  end

  def new_question
    self.cur_question = Question.create(self)
    self.author = cur_question.correct_book
    self.book = cur_question.correct_author
    self.answer = cur_question.correct_answer
    self.save!
  end

  def check_answer(idx)
    if idx.to_i == self.answer
      self.score += 100
    else
      self.over = true
    end
    self.save!
  end

  def over?
    self.over
  end
end

app/models/sentence.rb
class Sentence
  attr_accessor :author, :book, :content

  def self.random
    book = Book.all.sample
    sentence = Sentence.new
    sentence.book, sentence.author = book, book.author
    sentence.content = Sentence.pick_sentence(book.content)
    sentence
  end

  def self.pick_sentence(text)
    sentences = text.split(/(?<=[?.!])/)
    sentences.map!(&:strip).select!{|s| s.length >= 150}.sort_by{|a| a.length }
    len = sentences.length
    sentences[len/3..len*2/3].sample.gsub(/\n|\r\n/, " ")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

end

app/controllers/page_controller.rb
class PageController < ApplicationController
	def home

	end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def show
    @quiz = Quiz.create
    session[:quiz_id] = @quiz.id
    render "quiz"
  end

  def update
    @quiz = session[:quiz_id] ? Quiz.find(session[:quiz_id]) : nil
    puts session[:quiz_id]
    puts params
    choice = params[:answer_id]
    if !@quiz || !choice
      render text: "You have not played or picked an answer!"
    else
      puts "choice is #{choice}"
      puts "correct answer is #{@quiz.answer}"
      @quiz.check_answer(choice)
      if @quiz.over?
        render "over"
      else
        flash[:notice] = "another one!"
        @quiz.new_question
        @quiz.save!
        render "quiz"
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= "Who Wrote It" %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<div class="container center hero-unit">
<%= yield %>
</div>

<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/page/home.html.haml
%h1  Welcome to the Famous Dead Writers Quiz!
%p{:class => "description clear"} Test your knowledge of the works and writing styles of some of the world's most famous deceased writers! Click on the button below to take the challenge.
.center
	%a{:href => "#{quiz_url}", :class => "start"} Start Quiz

app/views/quizzes/over.html.haml
%h1.over Game Over

%p{class: "over"} Your score was #{ @quiz.score }

%a.again{ class: "over", href: "#{ quiz_url }"} Try Again?

app/views/quizzes/quiz.html.haml
%p{:class => "score"} Current score: #{ @quiz.score }


%blockquote #{@quiz.cur_question.sentence.content}

%h3 Who Wrote It?:

- count = 0
- @quiz.cur_question.choices.each do |name, id|
  - count += 1
  %form.choice{id: "choice-#{count}", action: "#{ quiz_url }", method: "POST"}
    %input{ type: "hidden", name: "_method", value: "PUT" }
    %input{ type: "hidden", name: "authenticity_token", value: "#{form_authenticity_token}" }
    %input{ type: "hidden", name: "answer_id", value: "#{ id }" }
    %input{ type: "submit", name: "answer", value: "#{ name }" }